import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Amplify} from 'aws-amplify';
import config from '../aws-exports'; // Adjust the path if necessary

Amplify.configure(config);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
